package edu.mayo.phenoportal.client.help;

public class FaqData {
    private static HelpRecord[] records;

    public static HelpRecord[] getRecords() {
        if (records == null) {
            records = getNewRecords();
        }
        return records;
    }

    public static HelpRecord[] getNewRecords() {

        // a FaqRecord contains the title and and the answer (in that order).
        // The text could be read in from an RCP call to read the file similar
        // to the Help guide.
        return new HelpRecord[] {
                new HelpRecord(
                        "I am a registered user, but unable to execute a query, why?",
                        "This is because the basic user does not have algorithm execution permissions. To run a query, the user must request an upgrade to the IRB verified (or super user). Please visit FAQ #2 to learn more about User Types and their privileges."),
                new HelpRecord(
                        "How many User Types are there and what are their privileges?",
                        "We have three types of users with defined roles and responsibilities. The types of users and their privileges are as follows:"
                                + "<ul>"
                                + "<li>"
                                + "<strong><u>Basic User:</u></strong>"
                                + " The basic user has read-only permissions for viewing algorithms (phenotype criteria) and the ability download algorithms."
                                + "</li>"
                                + "<li>"
                                + "<strong><u>IRB Verified User:</u></strong>"
                                + " The type of user is known as super-user and must have completed IRB training. The web-administrator will verify the IRB number while upgrading the user privileges from basic to super user. These types of users can upload new algorithms, execute and view query results, as well as download reports and data source."
                                + "</li>"
                                + "<li>"
                                + "<strong><u>Admin User:</u></strong>"
                                + " This user administers the whole website and reviews all operations of phenotype portal. They have full access to site management functions such as change/update phenotype tree, delete existing algorithms, re-assign/change phenotype tree classes for an existing algorithm."
                                + "</li>" + "</ul>" + ""),
                new HelpRecord(
                        "What kind of files does phenotype portal accept when uploading an algorithm?",
                        "This portal only accepts a zip file which contains xml, xsd, and html file types generated by NQF's MAT tool."),
                new HelpRecord(
                        "What types of files will be downloaded if I download a phenotype?",
                        "<ul>"
                                + "<li>You will receive a  zip file which contains xml, xsd and html files if you download the phenotype from the Criteria Tab</li>"
                                + "<li>You will receive a  pdf  and excel file if you are downloading the phenotype from the Summary, Demographics or Flowchart Tabs.</li>"
                                + "</ul>"),
                new HelpRecord(
                        "Do you have a common log-in without registering the real name and email similar to the I2b2.org link http://webservices.i2b2.org/webclient/?",
                        "No. We want every user to register to enjoy the functionality of this application."),
                new HelpRecord(
                        "Do you have a graphical representation of the phenotype work flow or execution of criteria?",
                        "Yes. When you execute a phenotype, the tab \"Workflow\" will be enabled. This chart will be an auto-generated flowchart by JBPMN5 and JBoss Drools Rules."),
                new HelpRecord("Can I run this app in my handheld device?", "Not at this time."),
                new HelpRecord(
                        "Can I print demographics and summary charts and flow charts?",
                        "Yes. Please click on the  chart tabs (i.e Summary, Demographics, Flowchart), find \"Print\" button located in bottom-right of the screen and click it."),
                new HelpRecord(
                        "Are there any restrictions  selecting the date range for algorithm execution? For example, can I execute an algorithm against a database for a date range of five years or more?",
                        "There are not any date range restrictions, but please note that a large date range will result a longer query/wait time.. The application will email you if the query takes more than a minute and inform you that the query is running in the background."),
                new HelpRecord(
                        "How can I contact you for further questions?",
                        "Please email us on at <a class=\"htpLinks\" href=\"mailto:phenotypeportal@informatics.mayo.edu\">phenotypeportal@informatics.mayo.edu</a>"),
                new HelpRecord(
                        "Is there additional documentation?",
                        "Please visit the <a class=\"htpLinks\" href=\"http://docs.phenotypeportal.org\">QDM Phenotyping Documentation</a>"),
                new HelpRecord(
                        "Is there an API demonstration?",
                        "Please visit the <a class=\"htpLinks\" href=\"http://api.phenotypeportal.org\">QDM Phenotyping API Demonstration</a>"),
                new HelpRecord(
                        "Is there a downloadable virtual machine image?",
                        "Please visit the <a class=\"htpLinks\" href=\"http://static.phenotypeportal.org/downloads/vm/sharp-htp.ova\">sharp-htp virtual machine image</a>"),
                new HelpRecord(
                        "Is there a Cypress execution report for MU Stage 2 CQMs?",
                        "Please visit the <a class=\"htpLinks\" href=\"http://api.phenotypeportal.org/executor/cypress/report\">Cypress execution report for MU Stage 2 CQMs</a>"),
                new HelpRecord(
                        "Is source code available for download?",
                        "Please visit the <a class=\"htpLinks\" href=\"https://github.com/SHARP-HTP/qdm-phenotyping\">QDM Phenotyping GitHub</a>")
        };

    }
}